/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.chcla15.mdsd.math.assignment3.ui.internal.Assignment3Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathAssignmentLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assignment3Activator.getInstance().getInjector("dk.sdu.mmmi.mdsd.MathAssignmentLanguage");
	}

}
