/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd.generator;

import com.google.common.collect.Iterables;
import com.google.common.collect.Iterators;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Div;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Expression;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.ExternalDef;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.ExternalUse;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Let;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.MathExp;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Minus;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Mult;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Num;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Parameter;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Plus;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.ResultStatement;
import dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Var;
import java.util.HashSet;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.StringExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final MathExp math = Iterators.<MathExp>filter(resource.getAllContents(), MathExp.class).next();
    fsa.generateFile("MathComputation.java", this.compile(math));
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("#!/bin/bash");
    _builder.newLine();
    _builder.append("javac MathComputation.java");
    _builder.newLine();
    _builder.append("java MathComputation");
    _builder.newLine();
    fsa.generateFile("compileAndRun.sh", _builder);
  }
  
  public CharSequence compile(final MathExp math) {
    CharSequence _xblockexpression = null;
    {
      final String className = "MathComputation";
      final Iterable<ExternalDef> externalDefs = Iterables.<ExternalDef>filter(math.getDeclarations(), ExternalDef.class);
      final Iterable<ResultStatement> resultStatements = Iterables.<ResultStatement>filter(math.getDeclarations(), ResultStatement.class);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("/*");
      _builder.newLine();
      _builder.append("* AUTO-GENERATED CODE!");
      _builder.newLine();
      _builder.append("*/");
      _builder.newLine();
      _builder.newLine();
      _builder.append("/*");
      _builder.newLine();
      _builder.append("* Imports");
      _builder.newLine();
      _builder.append("*/");
      _builder.newLine();
      _builder.append("import java.util.function.Function;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("/*");
      _builder.newLine();
      _builder.append("* Class");
      _builder.newLine();
      _builder.append("*/");
      _builder.newLine();
      _builder.append("public class ");
      _builder.append(className);
      _builder.append(" {");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("/*");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("* Fields");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("*/");
      _builder.newLine();
      {
        int _length = ((Object[])Conversions.unwrapArray(externalDefs, Object.class)).length;
        boolean _greaterThan = (_length > 0);
        if (_greaterThan) {
          _builder.append("\t");
          _builder.append("private Externals externals;");
          _builder.newLine();
        }
      }
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("/*");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("* Constructors");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("*/");
      _builder.newLine();
      {
        int _length_1 = ((Object[])Conversions.unwrapArray(externalDefs, Object.class)).length;
        boolean _greaterThan_1 = (_length_1 > 0);
        if (_greaterThan_1) {
          _builder.append("\t");
          _builder.append("public ");
          _builder.append(className, "\t");
          _builder.append("(Externals externals) {");
          _builder.newLineIfNotEmpty();
          _builder.append("\t");
          _builder.append("\t");
          _builder.append("this.externals = externals;");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("}");
          _builder.newLine();
          _builder.append("\t");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("/*");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("* External functions");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("*/");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("public static interface Externals {");
          _builder.newLine();
          {
            for(final ExternalDef externalDef : externalDefs) {
              _builder.append("\t");
              _builder.append("\t");
              String _generateExternalSignature = this.generateExternalSignature(externalDef);
              _builder.append(_generateExternalSignature, "\t\t");
              _builder.append(";");
              _builder.newLineIfNotEmpty();
            }
          }
          _builder.append("\t");
          _builder.append("}");
          _builder.newLine();
        } else {
          _builder.append("\t");
          _builder.append("public ");
          _builder.append(className, "\t");
          _builder.append("() { }");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("/*");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("* Public methods");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("*/");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("public void compute() {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("// Call compute on each result-statement");
      _builder.newLine();
      {
        for(final ResultStatement resultStatement : resultStatements) {
          _builder.append("\t\t");
          _builder.append("System.out.println(\"");
          String _label = resultStatement.getLabel();
          _builder.append(_label, "\t\t");
          _builder.append(" \" + compute");
          String _firstUpper = StringExtensions.toFirstUpper(this.convertTolegalJavaIdentifier(resultStatement.getLabel()));
          _builder.append(_firstUpper, "\t\t");
          _builder.append("());");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("/*");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("* Result statements");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("*/");
      _builder.newLine();
      {
        for(final ResultStatement resultStatement_1 : resultStatements) {
          _builder.append("\t");
          String _generatePrivateMethod = this.generatePrivateMethod(resultStatement_1);
          _builder.append(_generatePrivateMethod, "\t");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("/*");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("* Main methods");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("*/");
      _builder.newLine();
      {
        int _length_2 = ((Object[])Conversions.unwrapArray(externalDefs, Object.class)).length;
        boolean _greaterThan_2 = (_length_2 > 0);
        if (_greaterThan_2) {
          _builder.append("\t");
          _builder.append("public static void main(String[] args) {");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("\t");
          _builder.append("new ");
          _builder.append(className, "\t\t");
          _builder.append("(new Externals() {");
          _builder.newLineIfNotEmpty();
          _builder.append("\t");
          _builder.append("\t\t");
          _builder.append("@Override");
          _builder.newLine();
          {
            for(final ExternalDef externalDef_1 : externalDefs) {
              _builder.append("\t");
              _builder.append("\t\t");
              String _generateExternalSignature_1 = this.generateExternalSignature(externalDef_1);
              _builder.append(_generateExternalSignature_1, "\t\t\t");
              _builder.append(" {");
              _builder.newLineIfNotEmpty();
              _builder.append("\t");
              _builder.append("\t\t");
              _builder.append("\t");
              _builder.append("// TODO: Implement method");
              _builder.newLine();
              _builder.append("\t");
              _builder.append("\t\t");
              _builder.append("\t");
              _builder.append("throw new UnsupportedOperationException();");
              _builder.newLine();
              _builder.append("\t");
              _builder.append("\t\t");
              _builder.append("}");
              _builder.newLine();
            }
          }
          _builder.append("\t");
          _builder.append("\t");
          _builder.append("}).compute();");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("}");
          _builder.newLine();
        } else {
          _builder.append("\t");
          _builder.append("public static void main(String[] args) {");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("\t");
          _builder.append("new ");
          _builder.append(className, "\t\t");
          _builder.append("().compute();");
          _builder.newLineIfNotEmpty();
          _builder.append("\t");
          _builder.append("}");
          _builder.newLine();
        }
      }
      _builder.append("}");
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }
  
  public String generateExternalSignature(final ExternalDef exDef) {
    final EList<Parameter> parameters = exDef.getParameters();
    final StringBuilder parameterString = new StringBuilder();
    for (final Parameter parameter : parameters) {
      {
        int _length = parameterString.length();
        boolean _greaterThan = (_length > 0);
        if (_greaterThan) {
          parameterString.append(", ");
        }
        parameterString.append(parameter.getType().getName()).append(" ").append(parameter.getParameterName());
      }
    }
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public int ");
    String _name = exDef.getName();
    _builder.append(_name);
    _builder.append("(");
    _builder.append(parameterString);
    _builder.append(")");
    return _builder.toString();
  }
  
  public String generatePrivateMethod(final ResultStatement r) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("private int compute");
    String _firstUpper = StringExtensions.toFirstUpper(this.convertTolegalJavaIdentifier(r.getLabel()));
    _builder.append(_firstUpper);
    _builder.append("() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("return ");
    String _compile = this.compile(r.getExp());
    _builder.append(_compile, "\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  public String convertTolegalJavaIdentifier(final String s) {
    final String validChars = "[a-z]|[A-Z]|\\d|[_]";
    final HashSet<String> illegalChars = new HashSet<String>();
    String validIdentifier = new String(s);
    for (int i = 0; (i < s.length()); i++) {
      {
        final String myChar = s.substring(i, (i + 1));
        boolean _matches = myChar.matches(validChars);
        boolean _not = (!_matches);
        if (_not) {
          illegalChars.add(myChar);
        }
      }
    }
    for (final String illegalChar : illegalChars) {
      validIdentifier = validIdentifier.replace(illegalChar, "");
    }
    return validIdentifier;
  }
  
  public String compile(final Expression exp) {
    CharSequence _switchResult = null;
    boolean _matched = false;
    if (exp instanceof Plus) {
      _matched=true;
      StringConcatenation _builder = new StringConcatenation();
      String _compile = this.compile(((Plus)exp).getLeft());
      _builder.append(_compile);
      _builder.append("+");
      String _compile_1 = this.compile(((Plus)exp).getRight());
      _builder.append(_compile_1);
      _switchResult = _builder;
    }
    if (!_matched) {
      if (exp instanceof Minus) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        String _compile = this.compile(((Minus)exp).getLeft());
        _builder.append(_compile);
        _builder.append("-");
        String _compile_1 = this.compile(((Minus)exp).getRight());
        _builder.append(_compile_1);
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (exp instanceof Mult) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        String _compile = this.compile(((Mult)exp).getLeft());
        _builder.append(_compile);
        _builder.append("*");
        String _compile_1 = this.compile(((Mult)exp).getRight());
        _builder.append(_compile_1);
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (exp instanceof Div) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        String _compile = this.compile(((Div)exp).getLeft());
        _builder.append(_compile);
        _builder.append("/");
        String _compile_1 = this.compile(((Div)exp).getRight());
        _builder.append(_compile_1);
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (exp instanceof Num) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        int _value = ((Num)exp).getValue();
        _builder.append(_value);
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (exp instanceof Var) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("t");
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (exp instanceof Let) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("new Function<Integer, Integer>() {");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("@Override");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public Integer apply(Integer t) {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("return ");
        String _compile = this.compile(((Let)exp).getBody());
        _builder.append(_compile, "\t\t");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("}.apply(");
        String _compile_1 = this.compile(((Let)exp).getBinding());
        _builder.append(_compile_1);
        _builder.append(")");
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (exp instanceof ExternalUse) {
        _matched=true;
        CharSequence _xblockexpression = null;
        {
          final StringBuilder extArguments = new StringBuilder();
          EList<Expression> _arguments = ((ExternalUse)exp).getArguments();
          for (final Expression extExp : _arguments) {
            {
              int _length = extArguments.length();
              boolean _greaterThan = (_length > 0);
              if (_greaterThan) {
                extArguments.append(", ");
              }
              extArguments.append("(").append(this.compile(extExp)).append(")");
            }
          }
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("externals.");
          String _name = ((ExternalUse)exp).getExternal().getName();
          _builder.append(_name);
          _builder.append("(");
          _builder.append(extArguments);
          _builder.append(")");
          _xblockexpression = _builder;
        }
        _switchResult = _xblockexpression;
      }
    }
    if (!_matched) {
      throw new Error("Compile: Invalid expression");
    }
    String _plus = ("(" + _switchResult);
    return (_plus + ")");
  }
}
