/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd.validation;

import dk.sdu.mmmi.mdsd.validation.AbstractMathAssignmentLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageValidator extends AbstractMathAssignmentLanguageValidator {
}
