/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd;

import dk.sdu.mmmi.mdsd.AbstractMathAssignmentLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageRuntimeModule extends AbstractMathAssignmentLanguageRuntimeModule {
}
