/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd;

import dk.sdu.mmmi.mdsd.MathAssignmentLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageStandaloneSetup extends MathAssignmentLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new MathAssignmentLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
