/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd.mathAssignmentLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Use</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.mathAssignmentLanguage.ExternalUse#getExternal <em>External</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.mathAssignmentLanguage.ExternalUse#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.mathAssignmentLanguage.MathAssignmentLanguagePackage#getExternalUse()
 * @model
 * @generated
 */
public interface ExternalUse extends Expression
{
  /**
   * Returns the value of the '<em><b>External</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>External</em>' reference.
   * @see #setExternal(ExternalDef)
   * @see dk.sdu.mmmi.mdsd.mathAssignmentLanguage.MathAssignmentLanguagePackage#getExternalUse_External()
   * @model
   * @generated
   */
  ExternalDef getExternal();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.mathAssignmentLanguage.ExternalUse#getExternal <em>External</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>External</em>' reference.
   * @see #getExternal()
   * @generated
   */
  void setExternal(ExternalDef value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.mathAssignmentLanguage.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.mathAssignmentLanguage.MathAssignmentLanguagePackage#getExternalUse_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArguments();

} // ExternalUse
