/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathAssignmentLanguageScopeProvider extends DelegatingScopeProvider {
}
