/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd.ide;

import dk.sdu.mmmi.mdsd.ide.AbstractMathAssignmentLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageIdeModule extends AbstractMathAssignmentLanguageIdeModule {
}
