/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd.ide


/**
 * Use this class to register ide components.
 */
class MathAssignmentLanguageIdeModule extends AbstractMathAssignmentLanguageIdeModule {
}
