/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mmmi.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathAssignmentLanguageStandaloneSetup extends MathAssignmentLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new MathAssignmentLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
